language: scala
scala:
  - 2.11.7
jdk:
  - openjdk7
script:
  - gem install mime-types
  - sbt test doc publish
services: []
deploy:
  # upload documentation to a S3 bucket
  provider: s3
  region: eu-west-1
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  skip_cleanup: true
  local_dir: $TRAVIS_BUILD_DIR/target/scala-2.11/api
  upload-dir: api/nightly
  on:
    branch: develop

# branches:
#   only:
#     - master
#     - develop
notifications:
  email:
    - yohann.bredoux@gmail.com